#### Hoja de Trabajo No.3 
#### Métodos Numericos 1
#### José Rodrigo Oliveros González 22848

**Ejercicios a : d utilizando método JACOBI**

In [ ]:
import numpy as np
import pandas as pd

def JACOBI(A, b, max_iter=100, error=1e-2):
    """
    Argumentos:
    A: Matriz cuadrada(n x n)
    b: Vector (n)
    max_iter: Máximo número de iteraciones
    error: Tolerancia para convergencia
    
    Returns:
    tabla: Lista de iteraciones [i, x1, x2, ..., xn]
    solucion: Vector solución final 
    """
    # Numero de incognitas o ecuaciones a trabajar
    n = len(b)  

    # Programación defensiva
    if A.shape != (n, n):
        raise ValueError("La matriz A debe ser cuadrada, n filas n columnas. Vector b tiene n elementos")
    if np.any(np.diag(A) == 0):
        raise ValueError("La diagonal de A no puede tener ceros")
    
    # Inicializar tabla
    tabla = [] 
    x_actual = np.zeros(n)
    tabla.append([0] + x_actual.tolist())
    
    # Iteraciones
    for k in range(1, max_iter + 1):
        x_nuevo = np.zeros(n)
        
        for i in range(n):
            # Suma de a_ij * x_j para j != i (elimina la diagonal)
            suma = np.dot(A[i, :], x_actual) - A[i, i] * x_actual[i]
            x_nuevo[i] = (b[i] - suma) / A[i, i]
        
        # Agregar a la tabla
        tabla.append([k] + x_nuevo.tolist())
        
        # Porcentaje de error
        if np.linalg.norm(x_nuevo - x_actual) < error:
            break
            
        x_actual = x_nuevo.copy() # Para no perder los valores actuales
    
    return tabla, x_actual

print("\n--- Inciso a ---")
A0 = np.array([[1, 1, 3],
              [3, 5, 1],
              [4, 1, 2]], dtype=float)
b0 = np.array([3, 7, 4], dtype=float)

tabla0, sol0 = JACOBI(A0, b0, max_iter=5)

df0 = pd.DataFrame(tabla0, columns=['Iteración'] + [f'x{i+1}' for i in range(len(b0))])
print(df0)

print("\n--- Inciso b ---")
A1 = np.array([[5, -1, -1],
              [1, -1, 2],
              [3, -1, 2]], dtype=float)
b1 = np.array([3, 0, 4], dtype=float)

tabla1, sol1 = JACOBI(A1, b1, max_iter=5)
df1 = pd.DataFrame(tabla1, columns=['Iteración'] + [f'x{i+1}' for i in range(len(b1))])
print(df1)

print("\n--- Inciso c ---")
A2 = np.array([[1,2,4,8,16],
              [1,6,36,216,1296],
              [1,10,100,1000,10000],
              [1,20,400,8000,160000],
              [1,30,900,27000,810000]], dtype=float)
b2 = np.array([13.4, 30.4, 41.8,57.9,66.5], dtype=float)

tabla2, sol2 = JACOBI(A2, b2, max_iter=5)
df2 = pd.DataFrame(tabla2, columns=['Iteración'] + [f'x{i+1}' for i in range(len(b2))])
print(df2)

print("\n--- Inciso d ---")
A3 = np.array([
    [8, 0, 6, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 9, 0, 0, 0, 0, 5, 0, 2, 1, 0],
    [0, 1, 7, 0, 0, 1, 2, 0, 0, 1, 0],
    [0, 1, 0, 6, 0, 0, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 9, 0, 0, 0, 1, 1, 1],
    [0, 1, 0, 2, 0, 10, 1, 0, 3, 0, 0],
    [0, 0, 5, 0, 2, 2, 10, 0, 0, 0, 0],
    [0, 0, 0, 6, 1, 0, 0, 15, 0, 2, 0],
    [0, 2, 0, 0, 4, 0, 1, 1, 20, 1, 0],
    [0, 0, 0, 0, 0, 3, 0, 6, 5, 25, 1],
    [1, 0, 3, 1, 5, 0, 7, 0, 0, 1, 12]
], dtype=float)
b3 = np.array([1,5,8,0,8,1,0,3,0,1,2], dtype=float)

tabla3, sol3 = JACOBI(A3, b3, max_iter=30)
df3 = pd.DataFrame(tabla3, columns=['Iteración'] + [f'x{i+1}' for i in range(len(b3))])
print(df3)



--- Inciso a ---
   Iteración      x1      x2     x3
0          0    0.00   0.000   0.00
1          1    3.00   1.400   2.00
2          2   -4.40  -0.800  -4.70
3          3   17.90   4.980  11.20
4          4  -35.58 -11.580 -36.29
5          5  123.45  30.006  78.95

--- Inciso b ---
   Iteración     x1    x2    x3
0          0  0.000  0.00  0.00
1          1  0.600 -0.00  2.00
2          2  1.000  4.60  1.10
3          3  1.740  3.20  2.80
4          4  1.800  7.34  0.99
5          5  2.266  3.78  2.97

--- Inciso c ---
   Iteración         x1         x2        x3        x4        x5
0          0   0.000000   0.000000  0.000000  0.000000  0.000000
1          1  13.400000   5.066667  0.418000  0.007238  0.000082
2          2   1.535453   0.047050 -0.303252 -0.029646 -0.000828
3          3  14.769320   7.876332  0.777181  0.038646  0.001404
4          4  -5.793017  -3.752424 -1.044151 -0.081231 -0.002380
5          5  25.769373  15.735379  1.901440  0.117142  0.004096

--- Inciso d -

**Ejercicios a : d utilizando método GAUSS SEIDEL**

In [144]:
import numpy as np
import pandas as pd

def gauss_seidel(A, b, x0=None, error=1e-2, max_iter=1000):
    """
    Argumentos:
        A: Matriz de coeficientes (n x n)
        b: Vector (n)
        x0: Vector inicial (por si tenemos idea de donde esta la solución)
        error: Tolerancia para convergencia
        max_iter: Número máximo de iteraciones
    
    Retorna:
        tabla: Lista de interaciones[i, x1, x2, ...]
        solucion: Vector solución
    """
    # Numero de variables que vamos a resolver
    n = len(b)
    
    # Programación defensiva
    if A.shape != (n, n):
        raise ValueError("La matriz A debe ser cuadrada, n filas n columnas. Vector b tiene n elementos")
    if np.any(np.diag(A) == 0):
        raise ValueError("La diagonal de A no puede tener ceros")
    
    # Inicialización
    tabla = []
    x = np.zeros(n) if x0 is None else x0.copy() # Si ya conocemos donde mas o menos esta la respuesta podemos iniciar un valor cercarno
    tabla.append([0] + x.tolist())
    
    # Iteraciones
    for k in range(1, max_iter + 1):
        x_anterior = x.copy()
        
        for i in range(n):
            # Suma de a_ij*x_j usando el valor actual
            suma = 0.0
            for j in range(n):
                if j != i:
                    suma += A[i, j] * x[j]
            
            # Actualización el valor actual
            x[i] = (b[i] - suma) / A[i, i]
        
        # Registrar iteración
        tabla.append([k] + x.tolist())
        
        # Porcentaje de eror
        if np.linalg.norm(x - x_anterior) < error:
            break
    
    return tabla, x


print("\n--- Inciso a ---")
A0 = np.array([[1, 1, 3],
              [3, 5, 1],
              [4, 1, 2]], dtype=float)
b0 = np.array([3, 7, 4], dtype=float)

tabla0, sol0 = gauss_seidel(A0, b0, max_iter=5)

df0 = pd.DataFrame(tabla0, columns=['Iteración'] + [f'x{i+1}' for i in range(len(b0))])
print(df0)

print("\n--- Inciso b ---")
A1 = np.array([[5, -1, -1],
              [1, -1, 2],
              [3, -1, 2]], dtype=float)
b1 = np.array([3, 0, 4], dtype=float)

tabla1, sol1 = gauss_seidel(A1, b1, max_iter=50)
df1 = pd.DataFrame(tabla1, columns=['Iteración'] + [f'x{i+1}' for i in range(len(b1))])
print(df1)

print("\n--- Inciso c ---")
A2 = np.array([[1,2,4,8,16],
              [1,6,36,216,1296],
              [1,10,100,1000,10000],
              [1,20,400,8000,160000],
              [1,30,900,27000,810000]], dtype=float)
b2 = np.array([13.4, 30.4, 41.8,57.9,66.5], dtype=float)

tabla2, sol2 = gauss_seidel(A2, b2, max_iter=50)
df2 = pd.DataFrame(tabla2, columns=['Iteración'] + [f'x{i+1}' for i in range(len(b2))])
print(df2)

print("\n--- Inciso d ---")
A3 = np.array([
    [8, 0, 6, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 9, 0, 0, 0, 0, 5, 0, 2, 1, 0],
    [0, 1, 7, 0, 0, 1, 2, 0, 0, 1, 0],
    [0, 1, 0, 6, 0, 0, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 9, 0, 0, 0, 1, 1, 1],
    [0, 1, 0, 2, 0, 10, 1, 0, 3, 0, 0],
    [0, 0, 5, 0, 2, 2, 10, 0, 0, 0, 0],
    [0, 0, 0, 6, 1, 0, 0, 15, 0, 2, 0],
    [0, 2, 0, 0, 4, 0, 1, 1, 20, 1, 0],
    [0, 0, 0, 0, 0, 3, 0, 6, 5, 25, 1],
    [1, 0, 3, 1, 5, 0, 7, 0, 0, 1, 12]
], dtype=float)
b3 = np.array([1,5,8,0,8,1,0,3,0,1,2], dtype=float)

tabla3, sol3 = gauss_seidel(A3, b3, max_iter=50)
df3 = pd.DataFrame(tabla3, columns=['Iteración'] + [f'x{i+1}' for i in range(len(b3))])
print(df3)



--- Inciso a ---
   Iteración         x1          x2          x3
0          0     0.0000     0.00000     0.00000
1          1     3.0000    -0.40000    -3.80000
2          2    14.8000    -6.72000   -24.24000
3          3    82.4400   -43.21600  -141.27200
4          4   470.0320  -252.36480  -811.88160
5          5  2691.0096 -1450.82944 -4654.60448

--- Inciso b ---
    Iteración        x1        x2        x3
0           0  0.000000  0.000000  0.000000
1           1  0.600000  0.600000  1.400000
2           2  1.000000  3.800000  2.400000
3           3  1.840000  6.640000  2.560000
4           4  2.440000  7.560000  2.120000
5           5  2.536000  6.776000  1.584000
6           6  2.272000  5.440000  1.312000
7           7  1.950400  4.574400  1.361600
8           8  1.787200  4.510400  1.574400
9           9  1.816960  4.965760  1.757440
10         10  1.944640  5.459520  1.812800
11         11  2.054464  5.680064  1.758336
12         12  2.087680  5.604352  1.670656
13         1

**Ejercicios a : d utilizando método  Descomposición LU**

In [145]:
import numpy as np
import pandas as pd

def lu_simplificado(A, b):
    """
    Resuelve Ax = b con descomposición LU manual
    Devuelve solo los resultados esenciales
    
    Argumentos:
        A: Matriz cuadrada (n x n)
        b: Vector (n)
    
    Returns:
        DataFrame con resultados
        Vector solución x
    """
    n = A.shape[0]
    U = A.copy().astype(float)
    L = np.eye(n)
    P = np.eye(n)
    
    for k in range(n-1):
        # Pivoteo parcial
        max_row = np.argmax(np.abs(U[k:, k])) + k
        if max_row != k:
            U[[k, max_row]] = U[[max_row, k]]
            P[[k, max_row]] = P[[max_row, k]]
            if k > 0:
                L[[k, max_row], :k] = L[[max_row, k], :k]
        
        # Eliminación
        for i in range(k+1, n):
            L[i, k] = U[i, k] / U[k, k]
            U[i, k:] -= L[i, k] * U[k, k:]
    
    # Resolver sistema
    y = np.linalg.solve(L, P @ b)
    x = np.linalg.solve(U, y)
    return x

A0 = np.array([[1, 1, 3],
              [3, 5, 1],
              [4, 1, 2]], dtype=float)
b0 = np.array([3, 7, 4], dtype=float)

# Resolver y mostrar
solucion0 = lu_simplificado(A0, b0)

print("\n=== Inciso A ===")
print("\nVector solución:")
print(np.array2string(solucion0, precision=6, suppress_small=True))


A1 = np.array([[5, -1, -1],
              [1, -1, 2],
              [3, -1, 2]], dtype=float)
b1 = np.array([3, 0, 4], dtype=float)

# Resolver y mostrar
solucion1 = lu_simplificado(A1, b1)

print("\n=== Inciso B ===")
print("\nVector solución:")
print(np.array2string(solucion1, precision=6, suppress_small=True))

A2 = np.array([[1,2,4,8,16],
              [1,6,36,216,1296],
              [1,10,100,1000,10000],
              [1,20,400,8000,160000],
              [1,30,900,27000,810000]], dtype=float)
b2 = np.array([13.4, 30.4, 41.8,57.9,66.5], dtype=float)


# Resolver y mostrar
solucion2 = lu_simplificado(A2, b2)

print("\n=== Inciso C ===")
print("\nVector solución:")
print(np.array2string(solucion2, precision=6, suppress_small=True))


A3 = np.array([
    [8, 0, 6, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 9, 0, 0, 0, 0, 5, 0, 2, 1, 0],
    [0, 1, 7, 0, 0, 1, 2, 0, 0, 1, 0],
    [0, 1, 0, 6, 0, 0, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 9, 0, 0, 0, 1, 1, 1],
    [0, 1, 0, 2, 0, 10, 1, 0, 3, 0, 0],
    [0, 0, 5, 0, 2, 2, 10, 0, 0, 0, 0],
    [0, 0, 0, 6, 1, 0, 0, 15, 0, 2, 0],
    [0, 2, 0, 0, 4, 0, 1, 1, 20, 1, 0],
    [0, 0, 0, 0, 0, 3, 0, 6, 5, 25, 1],
    [1, 0, 3, 1, 5, 0, 7, 0, 0, 1, 12]
], dtype=float)
b3 = np.array([1,5,8,0,8,1,0,3,0,1,2], dtype=float)


# Resolver y mostrar
solucion3 = lu_simplificado(A3, b3)

print("\n=== Inciso D ===")
print("\nVector solución:")
print(np.array2string(solucion3, precision=6, suppress_small=True))


=== Inciso A ===

Vector solución:
[0.5 1.  0.5]

=== Inciso B ===

Vector solución:
[2.       5.333333 1.666667]

=== Inciso C ===

Vector solución:
[ 1.994643  6.278899 -0.304588  0.00843  -0.000095]

=== Inciso D ===

Vector solución:
[-0.765918  1.060052  1.195524 -0.045798  0.910642  0.161438 -0.812178
  0.15305  -0.256887  0.034196  0.026916]


**Explicaciones**

- ¿Cuántas iteraciones necesitó en los incisos anteriores para obtener convergencia en 2 cifras significativas? 

    - Con el método JACOBI solo fue posible resolver el ejercicio D, tomando 15 iteraciones. Con este mismo método los ejercicios a, b y c fallaron al tener un valor de xn cercano al infinito, en este caso fallaron a las 720, 4934 y 1409 iteraciones respectivamente. 

    - Con el metodo GAUSS SEIDEL tampoco fue posible resolverl el ejercicio A, sin embargo se obtuvieron resultados satisfactorios en los ejercicios b, c y d. Estos convergerieron en 2 cifras significativas al llegar a las 23, 49 y 4 iteraciones respectivamente. 

    - El método directo descomposición LU tuvo el mayor rango de acierto, con este método todos los ejercicios convergen en vectores solución como se muestra en los resultados del respectivo método.